# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7ab7cdecce172361a40e0ae9a0f57e25baa532dbae243719880533de26e977eb868aee8a477a57fe30ff332d85aa84f88b99d1bb6582893cd5dcb48f82fb762

test:
  secret_key_base: f6a37a80c62def61920f48ceddea9491e2a06a12fb60ea1779f84223d6de2769dca2461fdf4ab800b48943a558cf5b7dca0330ad0311284a0c6ba3c5af1aa2a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
